### ISSUE TITLE
Not grabbing my categories from the forms :(

### ISSUE THREAD

**Issue by kimhart** [kimhart/Project2_Wiki#1]
Hi Phil! Hoping you can help me sort through this issue I've had for the last two days. It's not recognizing my form input for the categories (on both new article and edit article). I can't move forward with my categories pages until these are linked.

I've gone into pry to make sure everything is seeded correctly (and it is), but it gives me an empty array when I run Category.articles. I thought that by assigning the name category_id to my form input, that it would assign that value to my category_id section of my article parameters... but I'm not having any luck. How do I make this happen?

Thanks!!

**Comment by phlco** [comment]
Seems like your article form should have an input for the category it's associated with.  I'm going to assume that in your `post /articles` I'll see something like `Article.create({category_id: params[:category_id]})`

Lemme check!

**Comment by phlco** [comment]
Everything looks ok in the forms.  Are you sure you have any articles with categories seeded in your DB?

Something like this should work:

```
a = Article.find(1)
a.categories
```

**Comment by kimhart** [comment]
Yeah, Meredith and I were messing around with that for a long time. It kept returning an empty array even though I seeded them with pre-set category IDs. There are articles with category_ids, they just don't show up when I do a.categories. It comes up as => [ ]

Now when I create new articles or edit the ones that are already on the page, it doesn't seem to assign them anything. I can't figure it out!

**Comment by phlco** [comment]
OH. It looks like your Articles and Categories are set up as a join model between articles and categories.

So there is no `category_id` on your Article model!  You need to use the ActiveRecord associations as follows:

```
a = Article.find(1)
c = Category.find(params[:category_id])
a.categories.push(c)
```
